"""Write lib/mission/mavlinkCommands.ts from MAVLink's own definition file.

The command and frame numbers in a mission file are MAVLink's. They are taken from
common.xml in the mavlink/mavlink repository, not typed by hand.

    python scripts/generate-mavlink-table.py path/to/common.xml
"""
import re
import sys
import xml.etree.ElementTree as ET

src = sys.argv[1]
root = ET.parse(src).getroot()


def clean(text):
    return re.sub(r"\s+", " ", (text or "").strip())


def enum(name):
    e = root.find(f".//enum[@name='{name}']")
    out = []
    for entry in e.findall("entry"):
        if entry.find("deprecated") is not None and name == "MAV_FRAME":
            pass  # still listed: old files use them
        out.append(
            {
                "value": int(entry.get("value")),
                "name": entry.get("name"),
                "description": clean(entry.findtext("description")),
                "params": {
                    int(p.get("index")): clean(p.get("label") or (p.text or "")).split(".")[0][:60]
                    for p in entry.findall("param")
                    if clean(p.get("label") or p.text) and (p.get("reserved") != "true")
                },
                "deprecated": entry.find("deprecated") is not None,
            }
        )
    return sorted(out, key=lambda x: x["value"])


cmds = enum("MAV_CMD")
frames = enum("MAV_FRAME")


def q(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


lines = [
    "// GENERATED by scripts/generate-mavlink-table.py from MAVLink's common.xml.",
    "// Do not edit by hand: run the script again against a newer common.xml.",
    "// Source: github.com/mavlink/mavlink, message_definitions/v1.0/common.xml",
    "",
    "export interface MavCommand {",
    "  name: string;",
    "  description: string;",
    "  /** What each of param1..7 means, where MAVLink says. */",
    "  params: Record<number, string>;",
    "}",
    "",
    "export const MAV_CMD: Record<number, MavCommand> = {",
]
for c in cmds:
    # mission files only hold NAV_, DO_, CONDITION_ and a few capture commands
    if not re.match(r"MAV_CMD_(NAV|DO|CONDITION|IMAGE|VIDEO|OBLIQUE|SET_CAMERA|PANORAMA|PAYLOAD)", c["name"]):
        continue
    params = ", ".join(f"{k}: {q(v)}" for k, v in sorted(c["params"].items()))
    lines.append(
        f"  {c['value']}: {{ name: {q(c['name'][8:])}, description: {q(c['description'][:200])}, params: {{ {params} }} }},"
    )
lines += ["};", "", "export const MAV_FRAME: Record<number, { name: string; description: string }> = {"]
for f in frames:
    lines.append(f"  {f['value']}: {{ name: {q(f['name'][10:])}, description: {q(f['description'][:200])} }},")
lines += ["};", ""]

open("lib/mission/mavlinkCommands.ts", "w", encoding="utf-8", newline="\n").write("\n".join(lines))
print("commands", sum(1 for line in lines if re.match(r"  \d+: \{ name", line)), "written")
