"""Build the app's table of MAVLink messages from MAVLink's own definitions.

    python scripts/generate-mavlink-messages.py <folder> [<revision>]

<folder> holds common.xml, standard.xml and minimal.xml from

    https://github.com/mavlink/mavlink/tree/master/message_definitions/v1.0

common.xml includes standard.xml, which includes minimal.xml. Together they are
the "common" dialect, which is what PX4 and ArduPilot both speak.

The output is lib/mavlink/messages.ts. Nothing in it is written by this app:
every name, number, type and unit is MAVLink's. What this script works out is
what MAVLink's documentation says a reader must work out for itself:

  - the order of a message's fields ON THE WIRE, which is not the order they
    are written in: largest type first, extension fields last, in their own
    order (mavlink.io, "Serialization", "Field Reordering");
  - CRC_EXTRA, one byte for each message, made from its name and its fields,
    which goes into a packet's checksum so that two ends that disagree about a
    message's layout reject each other's packets (the same page, "CRC_EXTRA
    Calculation").

scripts/verify-mavlink.mjs checks both, for every message, against pymavlink.
"""
import io
import json
import os
import re
import sys
import xml.etree.ElementTree as ET

if len(sys.argv) < 2:
    print(__doc__)
    sys.exit(2)
folder = sys.argv[1]
revision = sys.argv[2] if len(sys.argv) > 2 else 'unknown'

SIZE = {'uint64_t': 8, 'int64_t': 8, 'double': 8, 'uint32_t': 4, 'int32_t': 4, 'float': 4,
        'uint16_t': 2, 'int16_t': 2, 'uint8_t': 1, 'int8_t': 1, 'char': 1}


def crc_accumulate(data, crc=0xFFFF):
    """CRC-16/MCRF4XX, as MAVLink uses it."""
    for b in data:
        tmp = b ^ (crc & 0xFF)
        tmp = (tmp ^ (tmp << 4)) & 0xFF
        crc = ((crc >> 8) ^ (tmp << 8) ^ (tmp << 3) ^ (tmp >> 4)) & 0xFFFF
    return crc


def parse_type(text):
    """'uint8_t[8]' -> ('uint8_t', 8); 'uint8_t_mavlink_version' -> ('uint8_t', 0)."""
    m = re.match(r'^(\w+?)(?:\[(\d+)\])?$', text)
    base, n = m.group(1), int(m.group(2) or 0)
    if base == 'uint8_t_mavlink_version':
        base = 'uint8_t'
    if base not in SIZE:
        raise SystemExit(f'a type this script does not know: {text}')
    return base, n


messages = {}
enums = {}
seen = []


def read(name):
    if name in seen:
        return
    seen.append(name)
    root = ET.parse(os.path.join(folder, name)).getroot()
    for inc in root.findall('include'):
        read(inc.text.strip())
    for e in root.findall('enums/enum'):
        entry = enums.setdefault(e.get('name'), {'bitmask': False, 'values': {}})
        if e.get('bitmask') == 'true':
            entry['bitmask'] = True
        for v in e.findall('entry'):
            if v.get('value') is None:
                continue
            raw = v.get('value')
            value = int(raw, 0) if not raw.startswith('2**') else 2 ** int(raw[3:])
            entry['values'][value] = v.get('name')
    for m in root.findall('messages/message'):
        fields = []
        ext = False
        for child in m:
            if child.tag == 'extensions':
                ext = True
            elif child.tag == 'field':
                base, n = parse_type(child.get('type'))
                f = {'name': child.get('name'), 'type': base, 'length': n, 'ext': ext}
                if child.get('units'):
                    f['units'] = child.get('units')
                if child.get('enum'):
                    f['enum'] = child.get('enum')
                fields.append(f)
        plain = [f for f in fields if not f['ext']]
        # largest type first; python's sort keeps the written order among equals
        wire = sorted(plain, key=lambda f: -SIZE[f['type']]) + [f for f in fields if f['ext']]
        crc = crc_accumulate((m.get('name') + ' ').encode())
        for f in wire:
            if f['ext']:
                continue
            crc = crc_accumulate((f['type'] + ' ').encode(), crc)
            crc = crc_accumulate((f['name'] + ' ').encode(), crc)
            if f['length']:
                crc = crc_accumulate(bytes([f['length']]), crc)
        length = lambda fs: sum(SIZE[f['type']] * (f['length'] or 1) for f in fs)
        messages[int(m.get('id'))] = {
            'id': int(m.get('id')),
            'name': m.get('name'),
            'crcExtra': (crc & 0xFF) ^ (crc >> 8),
            # without the extension fields: what a MAVLink 1 packet carries
            'lengthV1': length(plain),
            'length': length(fields),
            'declared': [f['name'] for f in fields],
            'fields': wire,
        }


read('common.xml')
# the commands have a table of their own, lib/mission/mavlinkCommands.ts
enums.pop('MAV_CMD', None)

out = io.StringIO()
out.write('// GENERATED by scripts/generate-mavlink-messages.py from MAVLink\'s message definitions.\n')
out.write('// Do not edit by hand: run the script again against newer definitions.\n')
out.write(f'// Source: github.com/mavlink/mavlink, message_definitions/v1.0/{{common,standard,minimal}}.xml, revision {revision}.\n')
out.write('// MAVLink licenses what is generated from its definitions under the MIT licence (its COPYING file).\n')
out.write('// Checked, message by message, against pymavlink: scripts/verify-mavlink.mjs.\n\n')
out.write("export type MavType = 'uint64_t' | 'int64_t' | 'double' | 'uint32_t' | 'int32_t' | 'float' | 'uint16_t' | 'int16_t' | 'uint8_t' | 'int8_t' | 'char';\n\n")
out.write('export interface MavField {\n  name: string;\n  type: MavType;\n  /** How many, for an array; 0 for one value. A char array is a string. */\n  length: number;\n  /** An extension field: MAVLink 2 only, and after every other field. */\n  ext: boolean;\n  units?: string;\n  enum?: string;\n}\n\n')
out.write('export interface MavMessage {\n  id: number;\n  name: string;\n  /** One byte made from the name and the fields, which goes into the checksum. */\n  crcExtra: number;\n  /** Payload length without the extension fields, and with them. */\n  lengthV1: number;\n  length: number;\n  /** The field names in the order the definition writes them. */\n  declared: string[];\n  /** The fields in the order they are on the wire. */\n  fields: MavField[];\n}\n\n')
out.write('export interface MavEnum {\n  bitmask: boolean;\n  values: Record<number, string>;\n}\n\n')
out.write(f'export const MAVLINK_REVISION = {json.dumps(revision)};\n\n')
out.write('export const MAV_MESSAGES: Record<number, MavMessage> = {\n')
for mid in sorted(messages):
    out.write(f'  {mid}: {json.dumps(messages[mid], separators=(",", ":"))},\n')
out.write('};\n\n')
out.write('export const MAV_ENUMS: Record<string, MavEnum> = {\n')
for name in sorted(enums):
    e = enums[name]
    values = ','.join(f'{json.dumps(str(k)) if k > 2 ** 53 else k}:{json.dumps(v)}' for k, v in sorted(e['values'].items()))
    out.write(f'  {name}: {{bitmask:{"true" if e["bitmask"] else "false"},values:{{{values}}}}},\n')
out.write('};\n\n')
out.write('export const MAV_MESSAGE_ID: Record<string, number> = {\n')
for mid in sorted(messages):
    out.write(f'  {messages[mid]["name"]}: {mid},\n')
out.write('};\n')

here = os.path.dirname(os.path.abspath(__file__))
target = os.path.join(here, '..', 'lib', 'mavlink', 'messages.ts')
os.makedirs(os.path.dirname(target), exist_ok=True)
with io.open(target, 'w', encoding='utf-8', newline='\n') as f:
    f.write(out.getvalue())
print(f'{len(messages)} messages and {len(enums)} enums -> {os.path.normpath(target)} ({os.path.getsize(target) // 1024} KB)')
