"""Build the app's PX4 parameter reference from PX4's own documentation.

    python scripts/generate-px4-params.py <parameter_reference.md> [<version>]

The input is the parameter reference of ONE PX4 release, which PX4 generates
from its source code. For v1.16.0:

    https://raw.githubusercontent.com/PX4/PX4-Autopilot/v1.16.0/docs/en/advanced_config/parameter_reference.md

The output is public/data/px4-<version>-parameters.json. Nothing in it is
written by this app: every description, limit, default and unit is PX4's.
PX4's documentation is licensed CC BY 4.0, and the output says so.

A default in this file is the FIRMWARE's default. Choosing an airframe in the
ground station changes many parameters from it, so "differs from the default"
does not mean "somebody changed it by hand".
"""
import io
import json
import os
import re
import sys

if len(sys.argv) < 2:
    print(__doc__)
    sys.exit(2)
src = sys.argv[1]
version = sys.argv[2] if len(sys.argv) > 2 else 'v1.16.0'
text = io.open(src, encoding='utf-8').read().replace('\r\n', '\n')

HEAD = re.compile(r'^### (\S+) \(`([A-Za-z0-9_]+)`\) \{#[^}]*\}\s*$')
ITEM = re.compile(r'^- `([^`]+)`: ?(.*)$')


def number(cell):
    cell = cell.strip()
    if cell == '':
        return None
    try:
        v = float(cell)
    except ValueError:
        return None
    return int(v) if v.is_integer() and 'e' not in cell.lower() and '.' not in cell else v


def default_of(cell):
    """'Disabled (0)' is a name and a value; '201' is a value; '' is neither."""
    cell = cell.strip()
    if cell == '':
        return None, None
    m = re.match(r'^(.*)\((-?[0-9.eE+-]+)\)$', cell)
    if m:
        return number(m.group(2)), m.group(1).strip()
    return number(cell), None


def tidy(lines):
    return re.sub(r'\s+', ' ', ' '.join(lines)).strip()


groups = []
params = {}
group = None
lines = text.split('\n')
i = 0
while i < len(lines):
    line = lines[i]
    if line.startswith('## '):
        group = line[3:].strip()
        groups.append(group)
        i += 1
        continue
    m = HEAD.match(line)
    if not m:
        i += 1
        continue
    name, kind = m.group(1), m.group(2)
    i += 1
    body = []
    while i < len(lines) and not lines[i].startswith('### ') and not lines[i].startswith('## '):
        body.append(lines[i])
        i += 1

    # paragraphs until the first list or table
    paragraphs = []
    current = []
    values = {}
    bits = {}
    table = None
    mode = 'text'
    for k, b in enumerate(body):
        s = b.strip()
        if s == '**Values:**':
            mode = 'values'
        elif s == '**Bitmask:**':
            mode = 'bits'
        elif s.startswith('Reboot | minValue'):
            mode = 'table'
            if k + 2 < len(body):
                table = [c.strip() for c in body[k + 2].split('|')]
            break
        elif mode == 'text':
            if s == '':
                if current:
                    paragraphs.append(tidy(current))
                    current = []
            else:
                current.append(s)
        else:
            im = ITEM.match(s)
            if im:
                (values if mode == 'values' else bits)[im.group(1)] = im.group(2).strip()
    if current and mode == 'text':
        paragraphs.append(tidy(current))

    entry = {'group': group, 'type': kind, 'short': paragraphs[0] if paragraphs else ''}
    long = ' '.join(paragraphs[1:]).strip()
    # PX4 repeats the short description as the long one for many parameters
    if long and long.rstrip('.') != entry['short'].rstrip('.'):
        entry['long'] = long
    if values:
        entry['values'] = values
    if bits:
        entry['bits'] = bits
    if table and len(table) >= 6:
        entry['reboot_required'] = '&check;' in table[0]
        for key, cell in (('min', table[1]), ('max', table[2]), ('increment', table[3])):
            v = number(cell)
            if v is not None:
                entry[key] = v
        d, label = default_of(table[4])
        if d is not None:
            entry['default'] = d
        if label:
            entry['default_means'] = label
        if table[5]:
            entry['unit'] = table[5]
    if name in params:
        print('twice in the reference:', name)
    params[name] = entry

out = {
    'schema': 'flight-companion/px4-parameter-reference@1',
    'firmware': f'PX4 {version}',
    'source': f'https://github.com/PX4/PX4-Autopilot/blob/{version}/docs/en/advanced_config/parameter_reference.md',
    'licence': 'CC BY 4.0, the PX4 documentation authors. https://creativecommons.org/licenses/by/4.0/',
    'about': 'Every description, limit, default and unit is PX4\'s own, generated by PX4 from its source code. '
             'A default is the firmware\'s default: choosing an airframe changes many parameters from it.',
    'count': len(params),
    'groups': groups,
    'parameters': params,
}
here = os.path.dirname(os.path.abspath(__file__))
target = os.path.join(here, '..', 'public', 'data', f'px4-{version}-parameters.json')
os.makedirs(os.path.dirname(target), exist_ok=True)
with io.open(target, 'w', encoding='utf-8', newline='\n') as f:
    json.dump(out, f, ensure_ascii=False, separators=(',', ':'))
print(f'{len(params)} parameters in {len(groups)} groups -> {os.path.normpath(target)} ({os.path.getsize(target) // 1024} KB)')
with_default = sum(1 for p in params.values() if 'default' in p)
print(f'{with_default} have a default, {sum(1 for p in params.values() if "values" in p)} a list of values, '
      f'{sum(1 for p in params.values() if "bits" in p)} a bitmask, {sum(1 for p in params.values() if p.get("reboot_required"))} need a reboot')
